apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender
  labels:
    app: playlist-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-recommender
  template:
    metadata:
      labels:
        app: playlist-recommender
    spec:
      initContainers:
      - name: recommendation-rules
        image: gustavofcunha/recommendation_rules:v3
        volumeMounts:
        - name: shared-data
          mountPath: /modelo/data
      containers:
      - name: rest-api-server
        image: gustavofcunha/rest_api_server:v3
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: project2-pvc-gustavocunha