apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-gustavocunha
  namespace: gustavocunha
spec:
  storageClassName: default-storage-class-gustavocunha
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: gustavocunha
  volumeName: project2-pv2-gustavocunha
