apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc
  namespace: gustavocunha
spec:
  storageClassName: default-storage-class-gustavocunha
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostPath
      namespace: gustavocunha
