apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: gustavocunha
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 52027
      targetPort: 5000
      nodePort: 52111
  selector:
    app: playlist-recommender