#Dockerfile for the API Rest Server

FROM python:3.9-slim-bullseye

WORKDIR /app
COPY APIs/wsgi.py /app/
COPY APIs/requirements.txt /app/

RUN pip3 install -r requirements.txt
EXPOSE 9000

CMD ["flask", "run", "--host=0.0.0.0"]